#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#include "dsp/dsp.h"

// Generated by generator.fe
void setup_graph(void);
void trigger_voice1(int note, int accent);
void trigger_voice2(int note, int accent);
void trigger_voice3(int note, int accent);
void trigger_voice4(int note, int accent);
void trigger_voice5(int note, int accent);
void trigger_voice6(int note, int accent);

// The hardcoded sequence from generated code (if needed as fallback)
extern int sequence_data[16][12];

#define MAX_STEPS 256
static int custom_sequence[MAX_STEPS][12];
static int sequence_length = 0;

static int current_step = 0;
static int total_steps = 0;

static bool load_sequence(const char *filename) {
    FILE *f = fopen(filename, "r");
    if (!f) {
        fprintf(stderr, "Could not open sequence file: %s\n", filename);
        return false;
    }

    char line[256];
    int steps = 0;

    while (fgets(line, sizeof(line), f) && steps < MAX_STEPS) {
        // Ignore comments and empty lines
        if (line[0] == '#' || line[0] == '\n' || line[0] == '\r') continue;

        int values[12];
        int parsed = sscanf(line, "%d %d %d %d %d %d %d %d %d %d %d %d",
                            &values[0], &values[1], &values[2], &values[3],
                            &values[4], &values[5], &values[6], &values[7],
                            &values[8], &values[9], &values[10], &values[11]);
        
        if (parsed == 12) {
            for (int i = 0; i < 12; i++) {
                custom_sequence[steps][i] = values[i];
            }
            steps++;
        }
    }

    fclose(f);
    sequence_length = steps;
    printf("Loaded %d steps from %s\n", sequence_length, filename);
    return sequence_length > 0;
}

static void tick_callback(void) {
    int *s;
    if (sequence_length > 0) {
        s = custom_sequence[current_step % sequence_length];
    } else {
        // Fallback to the generated 16-step sequence_data
        s = sequence_data[current_step % 16];
    }

    trigger_voice1(s[0], s[1]);
    trigger_voice2(s[2], s[3]);
    trigger_voice3(s[4], s[5]);
    trigger_voice4(s[6], s[7]);
    trigger_voice5(s[8], s[9]);
    trigger_voice6(s[10], s[11]);

    if (sequence_length > 0) {
        current_step = (current_step + 1) % sequence_length;
    } else {
        current_step = (current_step + 1) % 16;
    }
    
    total_steps++;
}

int main(int argc, char **argv) {
    const char *seq_file = "sequence.txt";
    bool loop_forever = false;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--loop") == 0) {
            loop_forever = true;
        } else {
            seq_file = argv[i];
        }
    }

    if (!load_sequence(seq_file)) {
        printf("Falling back to hardcoded sequence_data from generator.\n");
    }

    if (SDL_Init(SDL_INIT_AUDIO | SDL_INIT_TIMER) < 0) {
        fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

    printf("Initializing DSP...\n");
    dsp_init(tick_callback);
    dsp_set_tick(0.125); // 120 BPM 16th notes
    dsp_set_stream("wrapper_out.raw");

    printf("Setting up graph from generated C code...\n");
    setup_graph();

    printf("Playing sequence... %s\n", loop_forever ? "(Press Ctrl+C to stop)" : "(4 loops)");
    
    int length_to_play = sequence_length > 0 ? sequence_length : 16;

    while (loop_forever || total_steps < length_to_play * 4) {
        SDL_Delay(10);
    }

    printf("Done.\n");
    SDL_Quit();
    return 0;
}
