(do-file "common.fe")
(do-file "dsp.fe")

(ui:set-scale 2)

; Initialize our audio nodes
(= osc (dsp:new 'osc))
(= amp (dsp:new 'line)) ; Use a line node for smooth amplitude changes
(= mul (dsp:new 'math))
(= dac (dsp:new 'dac))

; Create the audio graph
(dsp:link osc 'out mul 'in)
(dsp:link amp 'out mul 'in2)
(dsp:link mul 'out dac 'left)
(dsp:link mul 'out dac 'right)

; Set the math node to multiply its inputs
(dsp:send mul "set in * in2")

(func on-midi (type ch note velocity)
  ; Check if it's a 'note-on' message with velocity > 0
  (if (and (is type 'note-on) (< 0 velocity))
    (do
      ; Set oscillator frequency based on the MIDI note number
      (dsp:set osc 'freq (mtof note))
      ; Ramp amplitude to 1 over 10ms
      (dsp:send amp "begin 1 0.01")
    )
  )
  ; Check if it's a 'note-off' message or 'note-on' with velocity 0
  (if (or (is type 'note-off') (is velocity 0))
    ; Ramp amplitude to 0 over 10ms
    (dsp:send amp "begin 0 0.01")
  )
)